//! Split out of file_sync.rs.

#[allow(unused_imports)]
use super::*;

pub(crate) fn parse_script_filename(path: &Path) -> Option<(String, Option<String>, String)> {
    let fname = path.file_name()?.to_str()?;
    // Order matters: ".server.lua" also ends with ".lua", so the longer
    // suffixes must be tried first.
    let (base, ext) = if let Some(b) = fname.strip_suffix(".server.lua") {
        (b, "server.lua")
    } else if let Some(b) = fname.strip_suffix(".client.lua") {
        (b, "client.lua")
    } else if let Some(b) = fname.strip_suffix(".luau") {
        (b, "luau")
    } else {
        (fname.strip_suffix(".lua")?, "lua")
    };

    // Container script: the folder name is the object's name (init.server.lua, etc.)
    if base == "init" {
        let parent_dir = path.parent()?.file_name()?.to_str()?;
        if let Some((dir_name, dir_uuid)) = parent_dir.rsplit_once('_') {
            if is_short_uuid(dir_uuid) {
                return Some((dir_name.to_string(), Some(dir_uuid.to_string()), ext.to_string()));
            }
        }
        return Some((parent_dir.to_string(), None, ext.to_string()));
    }

    // Leaf script: only the 8-character short UUID suffix generated by layout is recognised.
    // A numeric suffix ("Health_2") is NO LONGER parsed; layout never produces such a name, and
    // parsing it broke the name of a real object called "Health_2".
    if let Some((name_part, potential_suffix)) = base.rsplit_once('_') {
        if is_short_uuid(potential_suffix) {
            return Some((name_part.to_string(), Some(potential_suffix.to_string()), ext.to_string()));
        }
    }

    Some((base.to_string(), None, ext.to_string()))
}

/// Is this the short UUID suffix generated by layout? (exactly 8 characters, all hex)
pub(crate) fn is_short_uuid(s: &str) -> bool {
    s.len() == 8 && s.chars().all(|c| c.is_ascii_hexdigit())
}

pub(crate) fn is_script_class(class_name: &str) -> bool {
    matches!(class_name, "Script" | "LocalScript" | "ModuleScript")
}

/// Finds the script node for a `Name.meta.json` or `init.meta.json` file.
///
/// The rule is the same as in layout.rs:
///
/// - `init.meta.json`  -> the node is the CONTAINING FOLDER itself (container script)
/// - `Name.meta.json`  -> the node is the folder's child called `Name`
///
/// On a name clash layout appends an 8-character short UUID to the file name; that suffix
/// is parsed here too, otherwise two scripts with the same name would be mixed up.
pub(crate) fn meta_target(dm: &crate::model::DataModel, path: &Path) -> Option<uuid::Uuid> {
    let fname = path.file_name()?.to_str()?;
    let base = fname.strip_suffix(".meta.json")?;
    let dir_name = path.parent()?.file_name()?.to_str()?;

    let divide = |s: &str| -> (String, String) {
        match s.rsplit_once('_') {
            Some((n, k)) if is_short_uuid(k) => (n.to_string(), k.to_string()),
            _ => (s.to_string(), String::new()),
        }
    };

    let (dir_clean, dir_short) = divide(dir_name);

    let dir_node = dm.get_all_instances().iter().find_map(|(u, n)| {
        if n.name == dir_clean && (dir_short.is_empty() || u.to_string().starts_with(&dir_short)) {
            Some(*u)
        } else {
            None
        }
    });

    if base == "init" {
        // Container script: the folder itself must be a script node.
        return dir_node.filter(|u| {
            dm.get_instance(u)
                .map(|n| is_script_class(&n.class_name))
                .unwrap_or(false)
        });
    }

    let (base_clean, base_short) = divide(base);
    let parent_ref = dir_node?;
    let parent_entry = dm.get_instance(&parent_ref)?;

    parent_entry.children.iter().find_map(|cid| {
        let c = dm.get_instance(cid)?;
        if c.name == base_clean
            && is_script_class(&c.class_name)
            && (base_short.is_empty() || cid.to_string().starts_with(&base_short))
        {
            Some(*cid)
        } else {
            None
        }
    })
}

/// Finds the node that owns a raw-content file (such as .txt).
/// Uses the same naming rules as meta_target.
pub(crate) fn raw_file_target(
    dm: &crate::model::DataModel,
    path: &Path,
    file_ext: &str,
    class_str: &str,
) -> Option<uuid::Uuid> {
    let fname = path.file_name()?.to_str()?;
    let base = fname.strip_suffix(&format!(".{}", file_ext))?;
    let dir_name = path.parent()?.file_name()?.to_str()?;

    let divide = |s: &str| -> (String, String) {
        match s.rsplit_once('_') {
            Some((n, k)) if is_short_uuid(k) => (n.to_string(), k.to_string()),
            _ => (s.to_string(), String::new()),
        }
    };

    let (dir_clean, dir_short) = divide(dir_name);
    let dir_node = dm.get_all_instances().iter().find_map(|(u, n)| {
        if n.name == dir_clean && (dir_short.is_empty() || u.to_string().starts_with(&dir_short)) {
            Some(*u)
        } else {
            None
        }
    });

    if base == "init" {
        return dir_node.filter(|u| {
            dm.get_instance(u).map(|n| n.class_name == class_str).unwrap_or(false)
        });
    }

    let (base_clean, base_short) = divide(base);
    let parent_ref = dir_node?;
    let parent_entry = dm.get_instance(&parent_ref)?;

    parent_entry.children.iter().find_map(|cid| {
        let c = dm.get_instance(cid)?;
        if c.name == base_clean
            && c.class_name == class_str
            && (base_short.is_empty() || cid.to_string().starts_with(&base_short))
        {
            Some(*cid)
        } else {
            None
        }
    })
}
