--[[
PUT YOUR PRODUCT IDS IN REPLICATEDSTORAGE.PRODUCT_IDS
SET GAME AVATAR TYPE TO R6
ALLOW STUDIO API ACCESS
ALLOW THIRD PARTY SALES (OPTIONAL)

FOR GROWING SYSTEM CHECK SERVERSTORAGE.PLANTHANDLER AND REPLICATEDSTORAGE.PLANT_MODULE

ITEM CONFIGURATION IS LOCATED IN REPLICATEDSTORAGE.ITEM_MODULE (YOU CAN CHANGE BASE WEIGHT, VALUE PER KG AND CHANCE TO GROW HUGE)
FOR SEED STUFF CHECK REPLICATEDSTORAGE.SEEDDATA
FOR GEAR STUFF CHECK REPLICATEDSTORAGE.GEARDATA

TO CHANGE NAME IN LOADING SCREEN CHECK STARTERGUI.DATA, THAT IS WHERE THE GUI IS LOCATED
]]